// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RDP_MZ","status":true,"description":"Remote Desktop for RPG Maker MZ","parameters":{"secretKey":"c699ade57c06648d93","ipAddress":"ivorymonster.com","port":"10578","protocol":"http","updateInterval":""}},
{"name":"Dreamon_resolution","status":true,"description":"v1.0 | Adds a customizable resolution option to the Options menu with Auto Detect and common presets.","parameters":{"includeAuto":"true","commandName":"Resolution","restartText":"Restart now?","yesText":"Yes","noText":"No"}}
];
